apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chronos.fullname" . }}-secret
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
type: Opaque
data:
  CHRONOS_POSTGRES_URL: {{ printf "postgresql+asyncpg://%s:%s@%s-postgres:%d/%s" .Values.postgres.username .Values.postgres.password (include "chronos.fullname" .) (.Values.postgres.port | int) .Values.postgres.database | b64enc }}
  CHRONOS_REDIS_URL: {{ printf "redis://%s-redis:%d/0" (include "chronos.fullname" .) (.Values.redis.port | int) | b64enc }}
